/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alex' at '12/1/16 5:55 PM' with Gradle 2.13
 *
 * @author alex, @date 12/1/16 5:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
